# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :adhoc do
    match(
      git_url: 'https://github.com/jbabin91/AppCenter-Certificates.git',
      type: 'adhoc',
      git_user_email: 'jbabin91@gmail.com',
      force_for_new_devices: true,
      readonly: is_ci
    )
  end
end
